[version]
major = 0
minor = 1
patch = 0
label = ""

[release]
# Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.–.
life_cycle = "simplified"
##############
# simplified #
##############
# 1) alfa 
# 2) beta 
# 3) Release candidate
# 4) Stable release 
#    Stable release LTS
# 5) discontinued

##########
# custom #
##########
# 1) X stages 
# 2) discontinued
stage_development="alfa"

[release.version]
major = 0
minor = 0
patch = 0
label = ""


[build.version]
major = 0
minor = 0
patch = 0
label = ""